- hosts: hosts
  become: yes

  tasks:
  - name: cache update
    ansible.builtin.apt:
      update_cache: yes

  - name: User create
    ansible.builtin.user:
      name: ansible-worker

  - name: git install
    ansible.builtin.apt:
      name: git
      state: present

  - name: set public ssh
    ansible.posix.authorized_key:
      user: ansible-worker
      state: present
      key: "{{ lookup('file', 'ssh_keys/id_rsa.pub') }}"
      path: /home/ansible-worker/.ssh/id_rsa.pub
      manage_dir: false
    become_method: sudo

  - name: set private ssh
    ansible.builtin.template:
      src: ssh_keys/id_rsa
      dest: /home/ansible-worker/.ssh/id_rsa
      mode: 0600

  - name: Git clone iphilka repo
    ansible.builtin.git:
      repo: https://github.com/iphilka/stud-template.git
      dest: /home/ansible-worker/www/stud-template/
      clone: yes
      update: no

  - name: replace index.html
    ansible.builtin.copy:
      src: index.html
      dest: /home/ansible-worker/www/stud-template/index.html
      owner: ansible-worker
      group: ansible-worker
      mode: 0755

  - name: set read permissions for ansible-worker directory
    ansible.builtin.file:
      path: /home/ansible-worker
      owner: ansible-worker
      group: ansible-worker
      mode: 0755
      recurse: yes

  - name: nginx install
    ansible.builtin.apt:
      name: nginx
      state: present

  - name: copy index.html file
    ansible.builtin.template:
      src: index.html
      dest: /home/ansible-worker/www/index.html

  - name: nginx conf file
    ansible.builtin.template:
      src: ansible.iphilka.ru.conf
      dest: /etc/nginx/sites-available/ansible.iphilka.ru.conf
    notify: restart nginx

  - name: enable nginx site
    ansible.builtin.file:
      src: /etc/nginx/sites-available/ansible.iphilka.ru.conf
      dest: /etc/nginx/sites-enabled/ansible.iphilka.ru.conf
      state: link
  
  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted